version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/usr/src/backend
      - ./usr/src/backend/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - bang-redis
  frontend:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/frontend
      - ./usr/src/frontend/node_modules
    env_file:
      - ./client/.env.local
    depends_on:
      - backend
  bang-redis:
    image: "redis"
    hostname: redis
    ports:
      - "6379:6379"
    env_file:
      - ./backend/.env
