apiVersion: v1
kind: Service
metadata:
  name: todo-sub-service
spec:
  selector:
    app: todo-sub-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-sub-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-sub-backend
  template:
    metadata:
      labels:
        app: todo-sub-backend
    spec:
      containers:
        - name: todo-sub-backend
          image: bangarangler/todo-sub-backend:latest
          env:
            - name: MONGO_STRING
              valueFrom:
                secretKeyRef:
                  name: todo-sub-backend-secret
                  key: MONGO_STRING
