apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: frontend
          image: bangarangler/next-frontend:latest
          env:
            - name: NEXT_PUBLIC_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: client-secret
                  key: NEXT_PUBLIC_JWT_SECRET_KEY
          # envFrom:
          #   - secretRef:
          #       name: client-secret

