apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: bangarangler/next-frontend:latest
          env:
            - name: "REACT_APP_ENVIRONMENT"
              value: "PROD"
            - name: NEXT_PUBLIC_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: client-secret
                  key: NEXT_PUBLIC_JWT_SECRET_KEY
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
          # envFrom:
          #   - secretRef:
          #       name: client-secret

